In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("titles.csv")

In [7]:
df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7

In [8]:
df.tail()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
5801,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.9,39.0,0.966,NaN
5802,tm1108171,Edis Starlight,MOVIE,Rising star Edis's career journey with ups and...,2021,NaN,74,"['music', 'documentation']",[],NaN,NaN,NaN,NaN,1.036,8.5
5803,tm1045018,Clash,MOVIE,A man from Nigeria returns to his family in Ca...,2021,NaN,88,"['family', 'drama']","['NG', 'CA']",NaN,tt14620732,6.5,32.0,0.709,NaN
5804,tm1098060,Shadow Parties,MOVIE,A family faces destruction in a long-running c...,2021,NaN,116,"['action', 'thriller']",[],NaN,tt10168094,6.2,9.0,2.186,NaN
5805,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,0,"['family', 'comedy', 'animation']",[],1.0,tt13711094,8.8,16.0,0.979,10.0

In [10]:
df.shape

(5806, 15)

In [12]:
df.columns

Index(['id', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'genres', 'production_countries',
       'seasons', 'imdb_id', 'imdb_score', 'imdb_votes', 'tmdb_popularity',
       'tmdb_score'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5806 entries, 0 to 5805
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    5806 non-null   str
 1   title                 5805 non-null   str
 2   type                  5806 non-null   str
 3   description           5788 non-null   str
 4   release_year          5806 non-null   int64
 5   age_certification     3196 non-null   str
 6   runtime               5806 non-null   int64
 7   genres                5806 non-null   str
 8   production_countries  5806 non-null   str
 9   seasons               2047 non-null   float64
 10  imdb_id               5362 non-null   str
 11  imdb_score            5283 non-null   float64
 12  imdb_votes            5267 non-null   float64
 13  tmdb_popularity       5712 non-null   float64
 14  tmdb_score            5488 non-null   float64
dtypes: float64(5), int64(2), str(8)
memory usage: 680.5 KB

In [14]:
df.describe

<bound method NDFrame.describe of              id                                title   type  \
0      ts300399  Five Came Back: The Reference Films   SHOW
1       tm84618                          Taxi Driver  MOVIE
2      tm127384      Monty Python and the Holy Grail  MOVIE
3       tm70993                        Life of Brian  MOVIE
4      tm190788                         The Exorcist  MOVIE
...         ...                                  ...    ...
5801  tm1014599                            Fine Wine  MOVIE
5802  tm1108171                       Edis Starlight  MOVIE
5803  tm1045018                                Clash  MOVIE
5804  tm1098060                       Shadow Parties  MOVIE
5805   ts271048   Mighty Little Bheem: Kite Festival   SHOW

                                            description  release_year  \
0     This collection includes 12 World War II-era p...          1945
1     A mentally unstable Vietnam War veteran works ...          1976
2     King Arthur, accompanied by his squire, recrui...          1975
3     Brian Cohen is an average young Jewish man, bu...          1979
4     12-year-old Regan MacNeil begins to adapt an e...          1973
...                                                 ...           ...
5801  A beautiful love story that can happen between...          2021
5802  Rising star Edis's career journey with ups and...          2021
5803  A man from Nigeria returns to his family in Ca...          2021
5804  A family faces destruction in a long-running c...          2021
5805  With winter behind them, Bheem and his townspe...          2021

     age_certification  runtime                             genres  \
0                TV-MA       48                  ['documentation']
1                    R      113                 ['crime', 'drama']
2                   PG       91              ['comedy', 'fantasy']
3                    R       94                         ['comedy']
4                    R      133                         ['horror']
...                ...      ...                                ...
5801               NaN      100               ['romance', 'drama']
5802               NaN       74         ['music', 'documentation']
5803               NaN       88                ['family', 'drama']
5804               NaN      116             ['action', 'thriller']
5805               NaN        0  ['family', 'comedy', 'animation']

     production_countries  seasons     imdb_id  imdb_score  imdb_votes  \
0                  ['US']      1.0         NaN         NaN         NaN
1                  ['US']      NaN   tt0075314         8.3    795222.0
2                  ['GB']      NaN   tt0071853         8.2    530877.0
3                  ['GB']      NaN   tt0079470         8.0    392419.0
4                  ['US']      NaN   tt0070047         8.1    391942.0
...                   ...      ...         ...         ...         ...
5801               ['NG']      NaN  tt13857480         6.9        39.0
5802                   []      NaN         NaN         NaN         NaN
5803         ['NG', 'CA']      NaN  tt14620732         6.5        32.0
5804                   []      NaN  tt10168094         6.2         9.0
5805                   []      1.0  tt13711094         8.8        16.0

      tmdb_popularity  tmdb_score
0               0.600         NaN
1              27.612         8.2
2              18.216         7.8
3              17.505         7.8
4              95.337         7.7
...               ...         ...
5801            0.966         NaN
5802            1.036         8.5
5803            0.709         NaN
5804            2.186         NaN
5805            0.979        10.0

[5806 rows x 15 columns]>

In [17]:
df.isnull().sum()

id                         0
title                      1
type                       0
description               18
release_year               0
age_certification       2610
runtime                    0
genres                     0
production_countries       0
seasons                 3759
imdb_id                  444
imdb_score               523
imdb_votes               539
tmdb_popularity           94
tmdb_score               318
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.drop_duplicates(inplace = True)

In [22]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.replace(
    ['N/A','NULL',' ',''],np.nan,inplace=True
)

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5801,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.9,39.0,0.966,NaN
5802,tm1108171,Edis Starlight,MOVIE,Rising star Edis's career journey with ups and...,2021,NaN,74,"['music', 'documentation']",[],NaN,NaN,NaN,NaN,1.036,8.5
5803,tm1045018,Clash,MOVIE,A man from Nigeria returns to his family in Ca...,2021,NaN,88,"['family', 'drama']","['NG', 'CA']",NaN,tt14620732,6.5,32.0,0.709,NaN
5804,tm1098060,Shadow Parties,MOVIE,A family faces destruction in a long-running c...,2021,NaN,116,"['action', 'thriller']",[],NaN,tt10168094,6.2,9.0,2.186,NaN
5805,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,0,"['family', 'comedy', 'animation']",[],1.0,tt13711094,8.8,16.0,0.979,10.0

In [27]:
df.isnull().sum()

id                         0
title                      1
type                       0
description               18
release_year               0
age_certification       2610
runtime                    0
genres                     0
production_countries       0
seasons                 3759
imdb_id                  444
imdb_score               523
imdb_votes               539
tmdb_popularity           94
tmdb_score               318
dtype: int64

In [28]:
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [32]:
df['title'] = df['title'].str.title()
df['type'] = df['type'].str.title()
df['age_certification'] = df['age_certification'].str.title()
df['genres'] = df['genres'].str.title()
df['production_countries'] = df['production_countries'].str.title()

In [33]:
df['title'].value_counts()

title
Connected                             3
The Gift                              3
Taxi Driver                           2
Dostana                               2
Whispers                              2
                                     ..
Fine Wine                             1
Edis Starlight                        1
Clash                                 1
Shadow Parties                        1
Mighty Little Bheem: Kite Festival    1
Name: count, Length: 5749, dtype: int64

In [36]:
numeric_cols = [
    'release_year',
    'runtime',
    'seasons',
    'imdb_score',
    'imdb_votes',
    'tmdb_popularity',
    'tmdb_score'
]

In [38]:
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [5]:
df.describe()

,release_year,runtime,seasons,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
count,5806.000000,5806.000000,2047.000000,5283.000000,5.267000e+03,5712.000000,5488.000000
mean,2016.013434,77.643989,2.165608,6.533447,2.340719e+04,22.525660,6.818039
std,7.324883,39.474160,2.636207,1.160932,8.713432e+04,68.849177,1.171560
min,1945.000000,0.000000,1.000000,1.500000,5.000000e+00,0.009442,0.500000
25%,2015.000000,44.000000,1.000000,5.800000,5.210000e+02,3.155250,6.100000
50%,2018.000000,84.000000,1.000000,6.600000,2.279000e+03,7.478000,6.900000
75%,2020.000000,105.000000,2.000000,7.400000,1.014400e+04,17.775750,7.500000
max,2022.000000,251.000000,42.000000,9.600000,2.268288e+06,1823.374000,10.000000

In [10]:
df['runtime'] = pd.to_datetime(df['runtime'], errors='coerce')

In [14]:
df["genres"] = df["genres"].fillna("Unknown")

In [15]:
df["description"] = df["genres"].fillna("description")

In [16]:
df["type"] = df["type"].fillna("Unknown")

In [18]:
df["content_age"] = 2026-df["release_year"]

In [21]:
df["is_movie"] = (df["type"] == "MOVIE").astype(int)

In [22]:
df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,content_age,is_movie
0,ts300399,Five Came Back: The Reference Films,SHOW,['documentation'],1945,TV-MA,1970-01-01 00:00:00.000000048,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN,81,0
1,tm84618,Taxi Driver,MOVIE,"['crime', 'drama']",1976,R,1970-01-01 00:00:00.000000113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,50,1
2,tm127384,Monty Python and the Holy Grail,MOVIE,"['comedy', 'fantasy']",1975,PG,1970-01-01 00:00:00.000000091,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8,51,1
3,tm70993,Life of Brian,MOVIE,['comedy'],1979,R,1970-01-01 00:00:00.000000094,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8,47,1
4,tm190788,The Exorcist,MOVIE,['horror'],1973,R,1970-01-01 00:00:00.000000133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7,53,1

In [23]:
def watch_category(score):
    if score >= 8:
        return "Highly Rated"
    elif score >= 7:
        return "Good"
    elif score >= 6:
        return "Average"
    else:
        return "Low Rated"

df["watch_category"] = df["imdb_score"].apply(watch_category)

In [24]:
df[["title", "imdb_score", "watch_category"]].head()

                                 title  imdb_score watch_category
0  Five Came Back: The Reference Films         NaN      Low Rated
1                          Taxi Driver         8.3   Highly Rated
2      Monty Python and the Holy Grail         8.2   Highly Rated
3                        Life of Brian         8.0   Highly Rated
4                         The Exorcist         8.1   Highly Rated

In [29]:
def watch_category(score):
    if score >= 8:
        return "Highly Rated"
    elif score >= 7:
        return "Good"
    elif score >= 6:
        return "Average"
    else:
        return "Low Rated"

df["watch_category"] = df["imdb_score"].apply(watch_category)

In [30]:
df[["title", "imdb_score", "watch_category"]].head()

                                 title  imdb_score watch_category
0  Five Came Back: The Reference Films         NaN      Low Rated
1                          Taxi Driver         8.3   Highly Rated
2      Monty Python and the Holy Grail         8.2   Highly Rated
3                        Life of Brian         8.0   Highly Rated
4                         The Exorcist         8.1   Highly Rated

In [31]:
df["watch_category"].value_counts()

watch_category
Low Rated       2004
Average         1738
Good            1559
Highly Rated     505
Name: count, dtype: int64

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5806 entries, 0 to 5805
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    5806 non-null   str
 1   title                 5805 non-null   str
 2   type                  5806 non-null   str
 3   description           5806 non-null   str
 4   release_year          5806 non-null   int64
 5   age_certification     3196 non-null   str
 6   runtime               5806 non-null   datetime64[ns]
 7   genres                5806 non-null   str
 8   production_countries  5806 non-null   str
 9   seasons               2047 non-null   float64
 10  imdb_id               5362 non-null   str
 11  imdb_score            5283 non-null   float64
 12  imdb_votes            5267 non-null   float64
 13  tmdb_popularity       5712 non-null   float64
 14  tmdb_score            5488 non-null   float64
 15  content_age           5806 non-null   int64
 16  is_movie              5806 non-null   int64
 17  watch_category        5806 non-null   str
dtypes: datetime64[ns](1), float64(5), int64(3), str(9)
memory usage: 816.6 KB

In [34]:
df.isnull().sum()

id                         0
title                      1
type                       0
description                0
release_year               0
age_certification       2610
runtime                    0
genres                     0
production_countries       0
seasons                 3759
imdb_id                  444
imdb_score               523
imdb_votes               539
tmdb_popularity           94
tmdb_score               318
content_age                0
is_movie                   0
watch_category             0
dtype: int64

In [43]:
df["age_certification"]=df["age_certification"].fillna(0)
df["seasons"]=df["seasons"].fillna(0)
df["imdb_id"]=df["imdb_id"].fillna(0)
df["imdb_score"]=df["imdb_score"].fillna(0)
df["imdb_votes"] = df["imdb_votes"].fillna(0)
df["tmdb_popularity"] = df["tmdb_popularity"].fillna(0)
df["tmdb_score"] = df["tmdb_score"].fillna(0)

In [44]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.to_csv('Netflix_clean_data.csv', index='False')

In [3]:
!pip install sqlalchemy mysql-connector-python

Requirement already satisfied: sqlalchemy in c:\users\asus\python 12\new folder\lib\site-packages (2.0.52)
Requirement already satisfied: mysql-connector-python in c:\users\asus\python 12\new folder\lib\site-packages (26.7.0)
Requirement already satisfied: greenlet>=1 in c:\users\asus\python 12\new folder\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\python 12\new folder\lib\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    "mysql+mysqlconnector",
    username="root",
    password="Niteen@2004",
    host="localhost",
    port=3306,
    database="netflix_db"
)

engine = create_engine(connection_url)

In [18]:
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [19]:
df.to_sql(
    'netflix_data',
    con=engine,
    if_exists='replace',
    index=False
)

-1